# Additional MCQ Questions to reach 500+
# Run with: mix run priv/repo/seeds/mcq_additional.exs

alias OsnAiPrep.Repo
alias OsnAiPrep.Mcq.Question

defmodule McqAdder do
  def insert_all(questions) do
    for q <- questions do
      %Question{}
      |> Question.changeset(q)
      |> Repo.insert!()
    end
    length(questions)
  end
end

# More Python questions
python_extra = [
  %{question_en: "What is the output of: bool([]) in Python?", question_id: "Apa output dari: bool([]) di Python?", option_a_en: "False", option_a_id: "False", option_b_en: "True", option_b_id: "True", option_c_en: "None", option_c_id: "None", option_d_en: "Error", option_d_id: "Error", correct_answer: "A", explanation_en: "Empty sequences (list, tuple, string) are falsy in Python.", explanation_id: "Sequence kosong (list, tuple, string) adalah falsy di Python.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What does the zip() function do?", question_id: "Apa yang dilakukan fungsi zip()?", option_a_en: "Pairs elements from multiple iterables", option_a_id: "Memasangkan elemen dari beberapa iterable", option_b_en: "Compresses files", option_b_id: "Mengompresi file", option_c_en: "Sorts a list", option_c_id: "Mengurutkan list", option_d_en: "Reverses a list", option_d_id: "Membalikkan list", correct_answer: "A", explanation_en: "zip() creates an iterator of tuples pairing elements from input iterables.", explanation_id: "zip() membuat iterator tuple yang memasangkan elemen dari iterable input.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is a generator in Python?", question_id: "Apa itu generator di Python?", option_a_en: "A function that yields values lazily using yield", option_a_id: "Fungsi yang menghasilkan nilai secara lazy menggunakan yield", option_b_en: "A function that generates random numbers", option_b_id: "Fungsi yang generate angka acak", option_c_en: "A class constructor", option_c_id: "Constructor kelas", option_d_en: "A type of loop", option_d_id: "Tipe loop", correct_answer: "A", explanation_en: "Generators produce values on-demand using yield, saving memory for large sequences.", explanation_id: "Generator menghasilkan nilai on-demand menggunakan yield, menghemat memori untuk sequence besar.", topic: "python_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the difference between append() and extend()?", question_id: "Apa perbedaan antara append() dan extend()?", option_a_en: "append adds one element, extend adds all elements from iterable", option_a_id: "append menambah satu elemen, extend menambah semua elemen dari iterable", option_b_en: "They are the same", option_b_id: "Keduanya sama", option_c_en: "extend adds one element", option_c_id: "extend menambah satu elemen", option_d_en: "append adds multiple elements", option_d_id: "append menambah banyak elemen", correct_answer: "A", explanation_en: "list.append(x) adds x as single element; list.extend(iterable) adds each element from iterable.", explanation_id: "list.append(x) menambah x sebagai satu elemen; list.extend(iterable) menambah setiap elemen dari iterable.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is __init__ in Python classes?", question_id: "Apa itu __init__ di kelas Python?", option_a_en: "The constructor method called when creating an instance", option_a_id: "Method constructor yang dipanggil saat membuat instance", option_b_en: "A private variable", option_b_id: "Variabel private", option_c_en: "A class method", option_c_id: "Class method", option_d_en: "A static method", option_d_id: "Static method", correct_answer: "A", explanation_en: "__init__ initializes new objects with starting values and is called automatically.", explanation_id: "__init__ menginisialisasi objek baru dengan nilai awal dan dipanggil secara otomatis.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What does enumerate() return?", question_id: "Apa yang dikembalikan enumerate()?", option_a_en: "An iterator of (index, value) tuples", option_a_id: "Iterator dari tuple (index, value)", option_b_en: "Just the indices", option_b_id: "Hanya indeks", option_c_en: "Just the values", option_c_id: "Hanya nilai", option_d_en: "A dictionary", option_d_id: "Dictionary", correct_answer: "A", explanation_en: "enumerate() adds a counter to an iterable, returning (index, element) pairs.", explanation_id: "enumerate() menambahkan counter ke iterable, mengembalikan pasangan (index, element).", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is a set in Python?", question_id: "Apa itu set di Python?", option_a_en: "An unordered collection of unique elements", option_a_id: "Koleksi tidak terurut dari elemen unik", option_b_en: "An ordered list", option_b_id: "List terurut", option_c_en: "A dictionary without values", option_c_id: "Dictionary tanpa nilai", option_d_en: "A tuple", option_d_id: "Tuple", correct_answer: "A", explanation_en: "Sets store unique elements only and support set operations like union, intersection.", explanation_id: "Set menyimpan elemen unik saja dan mendukung operasi set seperti union, intersection.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the Global Interpreter Lock (GIL)?", question_id: "Apa itu Global Interpreter Lock (GIL)?", option_a_en: "A mutex that prevents multiple threads from executing Python bytecode simultaneously", option_a_id: "Mutex yang mencegah beberapa thread mengeksekusi bytecode Python secara bersamaan", option_b_en: "A global variable", option_b_id: "Variabel global", option_c_en: "A security feature", option_c_id: "Fitur keamanan", option_d_en: "A debugging tool", option_d_id: "Alat debugging", correct_answer: "A", explanation_en: "GIL limits true parallelism in CPython. Use multiprocessing for CPU-bound parallel tasks.", explanation_id: "GIL membatasi paralelisme sejati di CPython. Gunakan multiprocessing untuk tugas paralel CPU-bound.", topic: "python_basics", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is slicing in Python?", question_id: "Apa itu slicing di Python?", option_a_en: "Extracting a portion of a sequence using [start:stop:step]", option_a_id: "Mengekstrak bagian dari sequence menggunakan [start:stop:step]", option_b_en: "Cutting files into pieces", option_b_id: "Memotong file menjadi bagian", option_c_en: "Dividing numbers", option_c_id: "Membagi angka", option_d_en: "Splitting strings", option_d_id: "Memisahkan string", correct_answer: "A", explanation_en: "Slicing extracts subsequences: list[1:5] gets indices 1-4, list[::2] gets every 2nd element.", explanation_id: "Slicing mengekstrak subsequence: list[1:5] dapat indeks 1-4, list[::2] dapat setiap elemen ke-2.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What does the map() function do?", question_id: "Apa yang dilakukan fungsi map()?", option_a_en: "Applies a function to each element of an iterable", option_a_id: "Menerapkan fungsi ke setiap elemen dari iterable", option_b_en: "Creates a dictionary", option_b_id: "Membuat dictionary", option_c_en: "Finds elements in a list", option_c_id: "Menemukan elemen dalam list", option_d_en: "Sorts elements", option_d_id: "Mengurutkan elemen", correct_answer: "A", explanation_en: "map(func, iterable) applies func to each element, returning an iterator of results.", explanation_id: "map(func, iterable) menerapkan func ke setiap elemen, mengembalikan iterator hasil.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the filter() function?", question_id: "Apa itu fungsi filter()?", option_a_en: "Returns elements for which the function returns True", option_a_id: "Mengembalikan elemen yang fungsinya return True", option_b_en: "Removes all elements", option_b_id: "Menghapus semua elemen", option_c_en: "Sorts elements", option_c_id: "Mengurutkan elemen", option_d_en: "Counts elements", option_d_id: "Menghitung elemen", correct_answer: "A", explanation_en: "filter(func, iterable) keeps only elements where func(element) is True.", explanation_id: "filter(func, iterable) hanya menyimpan elemen di mana func(element) adalah True.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is a context manager (with statement)?", question_id: "Apa itu context manager (with statement)?", option_a_en: "A construct that manages resources automatically (setup and cleanup)", option_a_id: "Konstruksi yang mengelola resources secara otomatis (setup dan cleanup)", option_b_en: "A conditional statement", option_b_id: "Pernyataan kondisional", option_c_en: "A loop construct", option_c_id: "Konstruksi loop", option_d_en: "A function type", option_d_id: "Tipe fungsi", correct_answer: "A", explanation_en: "Context managers handle setup/cleanup automatically, commonly used for files: with open() as f.", explanation_id: "Context manager menangani setup/cleanup secara otomatis, biasa digunakan untuk file: with open() as f.", topic: "python_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the difference between deep copy and shallow copy?", question_id: "Apa perbedaan antara deep copy dan shallow copy?", option_a_en: "Deep copy creates new copies of nested objects, shallow copy doesn't", option_a_id: "Deep copy membuat salinan baru objek bersarang, shallow copy tidak", option_b_en: "They are the same", option_b_id: "Keduanya sama", option_c_en: "Shallow copy is deeper", option_c_id: "Shallow copy lebih dalam", option_d_en: "Deep copy is faster", option_d_id: "Deep copy lebih cepat", correct_answer: "A", explanation_en: "Shallow copy copies references to nested objects. Deep copy recursively copies all nested objects.", explanation_id: "Shallow copy menyalin referensi ke objek bersarang. Deep copy secara rekursif menyalin semua objek bersarang.", topic: "python_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What are f-strings in Python?", question_id: "Apa itu f-strings di Python?", option_a_en: "Formatted string literals that embed expressions: f'{var}'", option_a_id: "String literal terformat yang menyematkan ekspresi: f'{var}'", option_b_en: "File strings", option_b_id: "String file", option_c_en: "Float strings", option_c_id: "String float", option_d_en: "Function strings", option_d_id: "String fungsi", correct_answer: "A", explanation_en: "f-strings (Python 3.6+) allow embedding expressions directly in strings with {expr} syntax.", explanation_id: "f-strings (Python 3.6+) memungkinkan penyematan ekspresi langsung dalam string dengan sintaks {expr}.", topic: "python_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is __name__ == '__main__' used for?", question_id: "Untuk apa __name__ == '__main__' digunakan?", option_a_en: "To run code only when the script is executed directly, not imported", option_a_id: "Untuk menjalankan kode hanya saat script dieksekusi langsung, bukan diimpor", option_b_en: "To name the script", option_b_id: "Untuk memberi nama script", option_c_en: "To create the main function", option_c_id: "Untuk membuat fungsi main", option_d_en: "To import modules", option_d_id: "Untuk mengimpor modul", correct_answer: "A", explanation_en: "When a script runs directly, __name__ is '__main__'. When imported, it's the module name.", explanation_id: "Saat script berjalan langsung, __name__ adalah '__main__'. Saat diimpor, itu nama modul.", topic: "python_basics", difficulty: "medium", competition: "noai_prelim"}
]

IO.puts("Inserting additional Python questions...")
McqAdder.insert_all(python_extra)

# More NumPy questions
numpy_extra = [
  %{question_en: "What is np.linspace() used for?", question_id: "Untuk apa np.linspace() digunakan?", option_a_en: "Creates evenly spaced numbers over a specified interval", option_a_id: "Membuat angka berjarak sama dalam interval tertentu", option_b_en: "Creates random numbers", option_b_id: "Membuat angka acak", option_c_en: "Creates a linear regression", option_c_id: "Membuat regresi linear", option_d_en: "Creates a line plot", option_d_id: "Membuat plot garis", correct_answer: "A", explanation_en: "np.linspace(start, stop, num) creates num evenly spaced values from start to stop inclusive.", explanation_id: "np.linspace(start, stop, num) membuat num nilai berjarak sama dari start ke stop inklusif.", topic: "numpy", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What does np.where() do?", question_id: "Apa yang dilakukan np.where()?", option_a_en: "Returns elements chosen based on condition, or indices where condition is True", option_a_id: "Mengembalikan elemen berdasarkan kondisi, atau indeks di mana kondisi True", option_b_en: "Finds the location of a file", option_b_id: "Menemukan lokasi file", option_c_en: "Creates a new array", option_c_id: "Membuat array baru", option_d_en: "Sorts an array", option_d_id: "Mengurutkan array", correct_answer: "A", explanation_en: "np.where(cond, x, y) returns x where cond is True, y otherwise. Without x,y returns indices.", explanation_id: "np.where(cond, x, y) mengembalikan x di mana cond True, y jika tidak. Tanpa x,y mengembalikan indeks.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is np.clip() used for?", question_id: "Untuk apa np.clip() digunakan?", option_a_en: "Limits values to be within a specified range", option_a_id: "Membatasi nilai agar berada dalam rentang tertentu", option_b_en: "Removes values from array", option_b_id: "Menghapus nilai dari array", option_c_en: "Copies the array", option_c_id: "Menyalin array", option_d_en: "Reverses the array", option_d_id: "Membalikkan array", correct_answer: "A", explanation_en: "np.clip(arr, min, max) constrains all values to [min, max] range.", explanation_id: "np.clip(arr, min, max) membatasi semua nilai ke rentang [min, max].", topic: "numpy", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is np.stack() vs np.concatenate()?", question_id: "Apa perbedaan np.stack() dan np.concatenate()?", option_a_en: "stack creates a new axis, concatenate joins along existing axis", option_a_id: "stack membuat axis baru, concatenate menggabung di axis yang ada", option_b_en: "They are the same", option_b_id: "Keduanya sama", option_c_en: "concatenate creates new axis", option_c_id: "concatenate membuat axis baru", option_d_en: "stack is faster", option_d_id: "stack lebih cepat", correct_answer: "A", explanation_en: "np.stack joins arrays along a new axis, np.concatenate along an existing one.", explanation_id: "np.stack menggabung array di axis baru, np.concatenate di axis yang ada.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is np.flatten() vs np.ravel()?", question_id: "Apa perbedaan np.flatten() dan np.ravel()?", option_a_en: "flatten always returns a copy, ravel returns a view when possible", option_a_id: "flatten selalu mengembalikan copy, ravel mengembalikan view jika memungkinkan", option_b_en: "They are identical", option_b_id: "Keduanya identik", option_c_en: "ravel always copies", option_c_id: "ravel selalu menyalin", option_d_en: "flatten is faster", option_d_id: "flatten lebih cepat", correct_answer: "A", explanation_en: "flatten() always copies data, ravel() returns a view when memory is contiguous (more efficient).", explanation_id: "flatten() selalu menyalin data, ravel() mengembalikan view ketika memori kontinu (lebih efisien).", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What does np.einsum() do?", question_id: "Apa yang dilakukan np.einsum()?", option_a_en: "Performs Einstein summation convention for flexible array operations", option_a_id: "Melakukan konvensi penjumlahan Einstein untuk operasi array fleksibel", option_b_en: "Computes eigenvalues", option_b_id: "Menghitung eigenvalue", option_c_en: "Sums all elements", option_c_id: "Menjumlahkan semua elemen", option_d_en: "Creates einsum arrays", option_d_id: "Membuat array einsum", correct_answer: "A", explanation_en: "einsum enables concise specification of multi-array operations: dot products, transposes, traces, etc.", explanation_id: "einsum memungkinkan spesifikasi ringkas operasi multi-array: dot product, transpose, trace, dll.", topic: "numpy", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is np.expand_dims() used for?", question_id: "Untuk apa np.expand_dims() digunakan?", option_a_en: "Adds a new axis at the specified position", option_a_id: "Menambahkan axis baru di posisi tertentu", option_b_en: "Increases array values", option_b_id: "Meningkatkan nilai array", option_c_en: "Expands memory", option_c_id: "Memperluas memori", option_d_en: "Duplicates the array", option_d_id: "Menduplikasi array", correct_answer: "A", explanation_en: "expand_dims adds a dimension of size 1, useful for broadcasting: (3,) becomes (1,3) or (3,1).", explanation_id: "expand_dims menambahkan dimensi ukuran 1, berguna untuk broadcasting: (3,) menjadi (1,3) atau (3,1).", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What does np.squeeze() do?", question_id: "Apa yang dilakukan np.squeeze()?", option_a_en: "Removes axes of length 1 from the array shape", option_a_id: "Menghapus axis dengan panjang 1 dari shape array", option_b_en: "Compresses the array", option_b_id: "Mengompresi array", option_c_en: "Squeezes values together", option_c_id: "Menekan nilai bersama", option_d_en: "Reduces array size", option_d_id: "Mengurangi ukuran array", correct_answer: "A", explanation_en: "squeeze removes singleton dimensions: shape (1,3,1) becomes (3,).", explanation_id: "squeeze menghapus dimensi singleton: shape (1,3,1) menjadi (3,).", topic: "numpy", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is np.meshgrid() used for?", question_id: "Untuk apa np.meshgrid() digunakan?", option_a_en: "Creates coordinate matrices from coordinate vectors", option_a_id: "Membuat matriks koordinat dari vektor koordinat", option_b_en: "Creates a mesh network", option_b_id: "Membuat jaringan mesh", option_c_en: "Grids data for plotting", option_c_id: "Mengkisi data untuk plotting", option_d_en: "Creates a grid layout", option_d_id: "Membuat layout grid", correct_answer: "A", explanation_en: "meshgrid creates coordinate arrays for evaluating functions over a grid of x,y values.", explanation_id: "meshgrid membuat array koordinat untuk mengevaluasi fungsi pada grid nilai x,y.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the difference between np.array and np.asarray?", question_id: "Apa perbedaan antara np.array dan np.asarray?", option_a_en: "array always copies, asarray doesn't copy if already an array", option_a_id: "array selalu menyalin, asarray tidak menyalin jika sudah array", option_b_en: "They are the same", option_b_id: "Keduanya sama", option_c_en: "asarray always copies", option_c_id: "asarray selalu menyalin", option_d_en: "array is faster", option_d_id: "array lebih cepat", correct_answer: "A", explanation_en: "np.asarray avoids copying if input is already an ndarray with matching dtype.", explanation_id: "np.asarray menghindari penyalinan jika input sudah ndarray dengan dtype yang cocok.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What does np.unique() return?", question_id: "Apa yang dikembalikan np.unique()?", option_a_en: "Sorted unique elements of an array", option_a_id: "Elemen unik terurut dari array", option_b_en: "Duplicate elements", option_b_id: "Elemen duplikat", option_c_en: "Random elements", option_c_id: "Elemen acak", option_d_en: "First elements", option_d_id: "Elemen pertama", correct_answer: "A", explanation_en: "np.unique returns sorted unique values. Can also return indices and counts.", explanation_id: "np.unique mengembalikan nilai unik terurut. Juga bisa mengembalikan indeks dan hitungan.", topic: "numpy", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is np.cumsum() used for?", question_id: "Untuk apa np.cumsum() digunakan?", option_a_en: "Computes cumulative sum of elements", option_a_id: "Menghitung jumlah kumulatif elemen", option_b_en: "Counts elements", option_b_id: "Menghitung elemen", option_c_en: "Sums all elements", option_c_id: "Menjumlahkan semua elemen", option_d_en: "Custom sum function", option_d_id: "Fungsi sum kustom", correct_answer: "A", explanation_en: "cumsum returns running total: [1,2,3] becomes [1,3,6].", explanation_id: "cumsum mengembalikan total berjalan: [1,2,3] menjadi [1,3,6].", topic: "numpy", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What does np.allclose() check?", question_id: "Apa yang diperiksa np.allclose()?", option_a_en: "Whether two arrays are element-wise equal within a tolerance", option_a_id: "Apakah dua array sama element-wise dalam toleransi", option_b_en: "If arrays are identical", option_b_id: "Jika array identik", option_c_en: "If arrays are closed", option_c_id: "Jika array tertutup", option_d_en: "Array proximity in memory", option_d_id: "Kedekatan array di memori", correct_answer: "A", explanation_en: "allclose checks if |a-b| <= atol + rtol*|b| for all elements, useful for floating-point comparison.", explanation_id: "allclose memeriksa apakah |a-b| <= atol + rtol*|b| untuk semua elemen, berguna untuk perbandingan floating-point.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is np.linalg.norm() used for?", question_id: "Untuk apa np.linalg.norm() digunakan?", option_a_en: "Computes matrix or vector norms", option_a_id: "Menghitung norm matriks atau vektor", option_b_en: "Normalizes data", option_b_id: "Menormalisasi data", option_c_en: "Creates normal distribution", option_c_id: "Membuat distribusi normal", option_d_en: "Checks for normality", option_d_id: "Memeriksa normalitas", correct_answer: "A", explanation_en: "linalg.norm computes various norms: L2 (Euclidean), L1, Frobenius, infinity norm, etc.", explanation_id: "linalg.norm menghitung berbagai norm: L2 (Euclidean), L1, Frobenius, infinity norm, dll.", topic: "numpy", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What does np.random.seed() do?", question_id: "Apa yang dilakukan np.random.seed()?", option_a_en: "Sets the random number generator to a deterministic state for reproducibility", option_a_id: "Mengatur generator angka acak ke state deterministik untuk reprodusibilitas", option_b_en: "Plants a seed", option_b_id: "Menanam benih", option_c_en: "Creates new random numbers", option_c_id: "Membuat angka acak baru", option_d_en: "Resets all arrays", option_d_id: "Mereset semua array", correct_answer: "A", explanation_en: "Setting seed ensures same random numbers are generated each run, essential for reproducible experiments.", explanation_id: "Mengatur seed memastikan angka acak yang sama dihasilkan setiap run, penting untuk eksperimen yang dapat direproduksi.", topic: "numpy", difficulty: "easy", competition: "noai_prelim"}
]

IO.puts("Inserting additional NumPy questions...")
McqAdder.insert_all(numpy_extra)

# More ML questions
ml_extra = [
  %{question_en: "What is the difference between classification and regression?", question_id: "Apa perbedaan antara klasifikasi dan regresi?", option_a_en: "Classification predicts categories, regression predicts continuous values", option_a_id: "Klasifikasi memprediksi kategori, regresi memprediksi nilai kontinu", option_b_en: "They are the same", option_b_id: "Keduanya sama", option_c_en: "Regression is for categories", option_c_id: "Regresi untuk kategori", option_d_en: "Classification is for numbers", option_d_id: "Klasifikasi untuk angka", correct_answer: "A", explanation_en: "Classification outputs discrete classes (spam/not spam). Regression outputs continuous values (price, temperature).", explanation_id: "Klasifikasi menghasilkan kelas diskrit (spam/bukan spam). Regresi menghasilkan nilai kontinu (harga, suhu).", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is underfitting?", question_id: "Apa itu underfitting?", option_a_en: "Model is too simple to capture the underlying pattern in data", option_a_id: "Model terlalu sederhana untuk menangkap pola dalam data", option_b_en: "Model is too complex", option_b_id: "Model terlalu kompleks", option_c_en: "Model fits perfectly", option_c_id: "Model cocok sempurna", option_d_en: "Model runs too slowly", option_d_id: "Model berjalan terlalu lambat", correct_answer: "A", explanation_en: "Underfitting (high bias) occurs when model can't capture data complexity, performing poorly on both train and test.", explanation_id: "Underfitting (bias tinggi) terjadi ketika model tidak dapat menangkap kompleksitas data, berkinerja buruk di train dan test.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is a hyperparameter?", question_id: "Apa itu hyperparameter?", option_a_en: "A parameter set before training that controls the learning process", option_a_id: "Parameter yang diatur sebelum training yang mengontrol proses pembelajaran", option_b_en: "A parameter learned during training", option_b_id: "Parameter yang dipelajari selama training", option_c_en: "The model output", option_c_id: "Output model", option_d_en: "The input features", option_d_id: "Fitur input", correct_answer: "A", explanation_en: "Hyperparameters (learning rate, num layers) are set before training, unlike model parameters learned from data.", explanation_id: "Hyperparameter (learning rate, jumlah layer) diatur sebelum training, tidak seperti parameter model yang dipelajari dari data.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is ensemble learning?", question_id: "Apa itu ensemble learning?", option_a_en: "Combining multiple models to improve performance", option_a_id: "Menggabungkan beberapa model untuk meningkatkan performa", option_b_en: "Training one large model", option_b_id: "Melatih satu model besar", option_c_en: "Using one algorithm", option_c_id: "Menggunakan satu algoritma", option_d_en: "Parallel data processing", option_d_id: "Pemrosesan data paralel", correct_answer: "A", explanation_en: "Ensemble methods (Random Forest, Boosting) combine multiple models for better accuracy and robustness.", explanation_id: "Metode ensemble (Random Forest, Boosting) menggabungkan beberapa model untuk akurasi dan ketahanan yang lebih baik.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is bagging?", question_id: "Apa itu bagging?", option_a_en: "Bootstrap Aggregating - training models on random subsets with replacement", option_a_id: "Bootstrap Aggregating - melatih model pada subset acak dengan penggantian", option_b_en: "Putting models in bags", option_b_id: "Memasukkan model ke dalam tas", option_c_en: "Sequential model training", option_c_id: "Training model berurutan", option_d_en: "Feature selection method", option_d_id: "Metode seleksi fitur", correct_answer: "A", explanation_en: "Bagging creates diverse models by training on bootstrap samples, then averages predictions (reduces variance).", explanation_id: "Bagging membuat model beragam dengan training pada sampel bootstrap, lalu merata-ratakan prediksi (mengurangi variance).", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is boosting?", question_id: "Apa itu boosting?", option_a_en: "Sequential training where each model focuses on previous errors", option_a_id: "Training berurutan di mana setiap model fokus pada error sebelumnya", option_b_en: "Making models run faster", option_b_id: "Membuat model berjalan lebih cepat", option_c_en: "Parallel model training", option_c_id: "Training model paralel", option_d_en: "Data augmentation", option_d_id: "Augmentasi data", correct_answer: "A", explanation_en: "Boosting builds models sequentially, each correcting predecessors' mistakes (reduces bias). Examples: AdaBoost, XGBoost.", explanation_id: "Boosting membangun model secara berurutan, masing-masing memperbaiki kesalahan pendahulunya (mengurangi bias). Contoh: AdaBoost, XGBoost.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is XGBoost?", question_id: "Apa itu XGBoost?", option_a_en: "Extreme Gradient Boosting - an optimized gradient boosting library", option_a_id: "Extreme Gradient Boosting - library gradient boosting yang dioptimasi", option_b_en: "Extra Gradient Boost", option_b_id: "Extra Gradient Boost", option_c_en: "A neural network", option_c_id: "Neural network", option_d_en: "A clustering algorithm", option_d_id: "Algoritma clustering", correct_answer: "A", explanation_en: "XGBoost is highly efficient, regularized gradient boosting, winning many ML competitions.", explanation_id: "XGBoost adalah gradient boosting yang sangat efisien dan terregularisasi, memenangkan banyak kompetisi ML.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is feature engineering?", question_id: "Apa itu feature engineering?", option_a_en: "Creating new features from existing data to improve model performance", option_a_id: "Membuat fitur baru dari data yang ada untuk meningkatkan performa model", option_b_en: "Removing all features", option_b_id: "Menghapus semua fitur", option_c_en: "Automatic feature selection", option_c_id: "Seleksi fitur otomatis", option_d_en: "Data collection", option_d_id: "Pengumpulan data", correct_answer: "A", explanation_en: "Feature engineering transforms raw data into informative features: combining, scaling, encoding, creating interactions.", explanation_id: "Feature engineering mentransformasi data mentah menjadi fitur informatif: menggabung, scaling, encoding, membuat interaksi.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is one-hot encoding?", question_id: "Apa itu one-hot encoding?", option_a_en: "Converting categorical variables to binary vectors", option_a_id: "Mengkonversi variabel kategorikal ke vektor biner", option_b_en: "Heating the data", option_b_id: "Memanaskan data", option_c_en: "Encoding numbers", option_c_id: "Mengkodekan angka", option_d_en: "Encrypting data", option_d_id: "Mengenkripsi data", correct_answer: "A", explanation_en: "One-hot creates binary columns for each category: [red,blue,green] becomes [[1,0,0],[0,1,0],[0,0,1]].", explanation_id: "One-hot membuat kolom biner untuk setiap kategori: [merah,biru,hijau] menjadi [[1,0,0],[0,1,0],[0,0,1]].", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is label encoding?", question_id: "Apa itu label encoding?", option_a_en: "Converting categorical labels to integer values", option_a_id: "Mengkonversi label kategorikal ke nilai integer", option_b_en: "Creating labels", option_b_id: "Membuat label", option_c_en: "Removing labels", option_c_id: "Menghapus label", option_d_en: "Encrypting labels", option_d_id: "Mengenkripsi label", correct_answer: "A", explanation_en: "Label encoding assigns integers to categories: [cat,dog,bird] becomes [0,1,2]. Implies ordering.", explanation_id: "Label encoding menetapkan integer ke kategori: [kucing,anjing,burung] menjadi [0,1,2]. Mengimplikasikan urutan.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is stratified sampling?", question_id: "Apa itu stratified sampling?", option_a_en: "Sampling that preserves the class distribution in train/test splits", option_a_id: "Sampling yang mempertahankan distribusi kelas dalam split train/test", option_b_en: "Random sampling", option_b_id: "Sampling acak", option_c_en: "Sequential sampling", option_c_id: "Sampling berurutan", option_d_en: "Weighted sampling", option_d_id: "Sampling berbobot", correct_answer: "A", explanation_en: "Stratified sampling ensures train and test sets have the same proportion of each class as the original data.", explanation_id: "Stratified sampling memastikan set train dan test memiliki proporsi setiap kelas yang sama dengan data asli.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the confusion matrix?", question_id: "Apa itu confusion matrix?", option_a_en: "A table showing TP, TN, FP, FN for classification evaluation", option_a_id: "Tabel yang menunjukkan TP, TN, FP, FN untuk evaluasi klasifikasi", option_b_en: "A confusing visualization", option_b_id: "Visualisasi yang membingungkan", option_c_en: "Matrix multiplication result", option_c_id: "Hasil perkalian matriks", option_d_en: "Feature correlation table", option_d_id: "Tabel korelasi fitur", correct_answer: "A", explanation_en: "Confusion matrix shows actual vs predicted classes, enabling calculation of precision, recall, F1.", explanation_id: "Confusion matrix menunjukkan kelas aktual vs prediksi, memungkinkan perhitungan precision, recall, F1.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the elbow method?", question_id: "Apa itu metode elbow?", option_a_en: "A technique to find optimal K in K-means by plotting distortion vs K", option_a_id: "Teknik untuk menemukan K optimal di K-means dengan plot distorsi vs K", option_b_en: "A stretching exercise", option_b_id: "Latihan peregangan", option_c_en: "A feature selection method", option_c_id: "Metode seleksi fitur", option_d_en: "A regularization technique", option_d_id: "Teknik regularisasi", correct_answer: "A", explanation_en: "The elbow method plots within-cluster variance vs K; optimal K is where curve bends (elbow point).", explanation_id: "Metode elbow memplot variance dalam-cluster vs K; K optimal adalah di mana kurva membengkok (titik siku).", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is silhouette score?", question_id: "Apa itu silhouette score?", option_a_en: "A metric measuring how similar points are to their cluster vs other clusters", option_a_id: "Metrik yang mengukur seberapa mirip titik dengan clusternya vs cluster lain", option_b_en: "A shape detection score", option_b_id: "Skor deteksi bentuk", option_c_en: "A classification metric", option_c_id: "Metrik klasifikasi", option_d_en: "A regression error", option_d_id: "Error regresi", correct_answer: "A", explanation_en: "Silhouette score ranges from -1 to 1. High values mean well-clustered, negative means likely wrong cluster.", explanation_id: "Silhouette score berkisar dari -1 ke 1. Nilai tinggi berarti ter-cluster dengan baik, negatif berarti kemungkinan cluster salah.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is t-SNE used for?", question_id: "Untuk apa t-SNE digunakan?", option_a_en: "Dimensionality reduction for visualization of high-dimensional data", option_a_id: "Reduksi dimensi untuk visualisasi data berdimensi tinggi", option_b_en: "Classification", option_b_id: "Klasifikasi", option_c_en: "Regression", option_c_id: "Regresi", option_d_en: "Clustering", option_d_id: "Clustering", correct_answer: "A", explanation_en: "t-SNE (t-distributed Stochastic Neighbor Embedding) reduces dimensions while preserving local structure for 2D/3D visualization.", explanation_id: "t-SNE (t-distributed Stochastic Neighbor Embedding) mengurangi dimensi sambil mempertahankan struktur lokal untuk visualisasi 2D/3D.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"}
]

IO.puts("Inserting additional ML questions...")
McqAdder.insert_all(ml_extra)

total = Repo.aggregate(Question, :count)
IO.puts("\nTotal MCQ questions now: #{total}")
