# Bonus MCQ Questions to reach 500+ (40+ questions)
# Run with: mix run priv/repo/seeds/mcq_bonus.exs

alias OsnAiPrep.Repo
alias OsnAiPrep.Mcq.Question
import Ecto.Query

defmodule BonusSeeder do
  def insert_all(questions) do
    for q <- questions do
      %Question{}
      |> Question.changeset(q)
      |> Repo.insert!()
    end
    length(questions)
  end
end

bonus_questions = [
  # More CV practical (10)
  %{question_en: "What is image normalization?", question_id: "Apa itu normalisasi gambar?", option_a_en: "Scaling pixel values to a standard range (e.g., 0-1 or -1 to 1)", option_a_id: "Menskalakan nilai pixel ke rentang standar (mis., 0-1 atau -1 ke 1)", option_b_en: "Making images normal", option_b_id: "Membuat gambar normal", option_c_en: "Resizing images", option_c_id: "Mengubah ukuran gambar", option_d_en: "Rotating images", option_d_id: "Memutar gambar", correct_answer: "A", explanation_en: "Typically divide by 255 for 0-1 range. Use ImageNet mean/std for pretrained models.", explanation_id: "Biasanya bagi dengan 255 untuk rentang 0-1. Gunakan mean/std ImageNet untuk model pretrained.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is random horizontal flip?", question_id: "Apa itu random horizontal flip?", option_a_en: "Data augmentation that randomly mirrors images left-to-right", option_a_id: "Augmentasi data yang secara acak memirror gambar kiri-ke-kanan", option_b_en: "Flipping randomly", option_b_id: "Membalik secara acak", option_c_en: "Rotating 180 degrees", option_c_id: "Memutar 180 derajat", option_d_en: "Vertical flip", option_d_id: "Flip vertikal", correct_answer: "A", explanation_en: "Horizontal flip is safe for most tasks but not for text recognition or direction-sensitive tasks.", explanation_id: "Horizontal flip aman untuk sebagian besar tugas tapi tidak untuk pengenalan teks atau tugas sensitif arah.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is random crop?", question_id: "Apa itu random crop?", option_a_en: "Data augmentation that randomly extracts a portion of the image", option_a_id: "Augmentasi data yang secara acak mengekstrak bagian gambar", option_b_en: "Cropping farms", option_b_id: "Memotong pertanian", option_c_en: "Removing borders", option_c_id: "Menghapus border", option_d_en: "Resizing", option_d_id: "Mengubah ukuran", correct_answer: "A", explanation_en: "Random crop teaches model to recognize objects at different positions and scales.", explanation_id: "Random crop mengajarkan model untuk mengenali objek pada posisi dan skala berbeda.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is color jittering?", question_id: "Apa itu color jittering?", option_a_en: "Randomly changing brightness, contrast, saturation, hue", option_a_id: "Mengubah kecerahan, kontras, saturasi, hue secara acak", option_b_en: "Making colors jitter", option_b_id: "Membuat warna bergetar", option_c_en: "Fixing colors", option_c_id: "Memperbaiki warna", option_d_en: "Grayscale conversion", option_d_id: "Konversi grayscale", correct_answer: "A", explanation_en: "Color jitter makes models robust to lighting variations and camera differences.", explanation_id: "Color jitter membuat model tahan terhadap variasi pencahayaan dan perbedaan kamera.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the typical input size for pretrained CNNs?", question_id: "Apa ukuran input tipikal untuk CNN pretrained?", option_a_en: "224x224 or 256x256 pixels", option_a_id: "224x224 atau 256x256 pixel", option_b_en: "Any size works", option_b_id: "Ukuran apa pun bisa", option_c_en: "1000x1000 pixels", option_c_id: "1000x1000 pixel", option_d_en: "28x28 pixels", option_d_id: "28x28 pixel", correct_answer: "A", explanation_en: "ImageNet models typically use 224x224. Some models like EfficientNet use larger sizes.", explanation_id: "Model ImageNet biasanya menggunakan 224x224. Beberapa model seperti EfficientNet menggunakan ukuran lebih besar.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is center crop?", question_id: "Apa itu center crop?", option_a_en: "Extracting the central portion of an image", option_a_id: "Mengekstrak bagian tengah gambar", option_b_en: "Random crop from center", option_b_id: "Random crop dari tengah", option_c_en: "Cropping corners", option_c_id: "Memotong sudut", option_d_en: "Resizing to center", option_d_id: "Mengubah ukuran ke tengah", correct_answer: "A", explanation_en: "Center crop is deterministic, commonly used during inference/validation.", explanation_id: "Center crop deterministik, biasa digunakan selama inferensi/validasi.", topic: "computer_vision", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What are ImageNet mean and std values?", question_id: "Apa nilai mean dan std ImageNet?", option_a_en: "Mean: [0.485, 0.456, 0.406], Std: [0.229, 0.224, 0.225]", option_a_id: "Mean: [0.485, 0.456, 0.406], Std: [0.229, 0.224, 0.225]", option_b_en: "Mean: 0, Std: 1", option_b_id: "Mean: 0, Std: 1", option_c_en: "Mean: 0.5, Std: 0.5", option_c_id: "Mean: 0.5, Std: 0.5", option_d_en: "No normalization needed", option_d_id: "Tidak perlu normalisasi", correct_answer: "A", explanation_en: "Using these values when using ImageNet pretrained models is essential for good results.", explanation_id: "Menggunakan nilai ini saat menggunakan model pretrained ImageNet penting untuk hasil yang baik.", topic: "computer_vision", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is mixup augmentation?", question_id: "Apa itu augmentasi mixup?", option_a_en: "Blending two images and their labels with a ratio", option_a_id: "Mencampur dua gambar dan labelnya dengan rasio", option_b_en: "Mixing colors", option_b_id: "Mencampur warna", option_c_en: "Audio mixing", option_c_id: "Mencampur audio", option_d_en: "Data shuffling", option_d_id: "Shuffling data", correct_answer: "A", explanation_en: "Mixup creates new training samples: x = λx1 + (1-λ)x2, y = λy1 + (1-λ)y2.", explanation_id: "Mixup membuat sampel training baru: x = λx1 + (1-λ)x2, y = λy1 + (1-λ)y2.", topic: "computer_vision", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is cutout augmentation?", question_id: "Apa itu augmentasi cutout?", option_a_en: "Randomly masking out square regions of the image", option_a_id: "Secara acak meng-mask region persegi gambar", option_b_en: "Cutting images", option_b_id: "Memotong gambar", option_c_en: "Removing images", option_c_id: "Menghapus gambar", option_d_en: "Cropping", option_d_id: "Memotong", correct_answer: "A", explanation_en: "Cutout forces model to use more global information rather than relying on specific regions.", explanation_id: "Cutout memaksa model menggunakan informasi lebih global daripada mengandalkan region tertentu.", topic: "computer_vision", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is cutmix augmentation?", question_id: "Apa itu augmentasi cutmix?", option_a_en: "Cutting and pasting patches between images with proportional labels", option_a_id: "Memotong dan menempel patch antar gambar dengan label proporsional", option_b_en: "Cutting and mixing", option_b_id: "Memotong dan mencampur", option_c_en: "Similar to cutout", option_c_id: "Mirip cutout", option_d_en: "Color mixing", option_d_id: "Mencampur warna", correct_answer: "A", explanation_en: "CutMix replaces cutout region with patch from another image, combining mixup and cutout ideas.", explanation_id: "CutMix mengganti region cutout dengan patch dari gambar lain, menggabungkan ide mixup dan cutout.", topic: "computer_vision", difficulty: "hard", competition: "noai_prelim"},
  # More NLP practical (10)
  %{question_en: "What is padding in NLP?", question_id: "Apa itu padding dalam NLP?", option_a_en: "Adding special tokens to make all sequences the same length", option_a_id: "Menambahkan token khusus untuk membuat semua sequence panjangnya sama", option_b_en: "Adding extra spaces", option_b_id: "Menambahkan spasi ekstra", option_c_en: "Cushioning data", option_c_id: "Mengisi data", option_d_en: "Text formatting", option_d_id: "Format teks", correct_answer: "A", explanation_en: "Batches require same length. Pad shorter sequences with [PAD] token, use attention mask to ignore.", explanation_id: "Batch membutuhkan panjang sama. Pad sequence lebih pendek dengan token [PAD], gunakan attention mask untuk mengabaikan.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the [CLS] token?", question_id: "Apa itu token [CLS]?", option_a_en: "Special token at the start used for classification tasks", option_a_id: "Token khusus di awal yang digunakan untuk tugas klasifikasi", option_b_en: "Class label", option_b_id: "Label kelas", option_c_en: "Closing token", option_c_id: "Token penutup", option_d_en: "Clear token", option_d_id: "Token clear", correct_answer: "A", explanation_en: "In BERT, [CLS] token's embedding is used as the sentence representation for classification.", explanation_id: "Di BERT, embedding token [CLS] digunakan sebagai representasi kalimat untuk klasifikasi.", topic: "nlp", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the [SEP] token?", question_id: "Apa itu token [SEP]?", option_a_en: "Separator token between segments/sentences", option_a_id: "Token pemisah antara segmen/kalimat", option_b_en: "September token", option_b_id: "Token September", option_c_en: "Separate file token", option_c_id: "Token file terpisah", option_d_en: "Security token", option_d_id: "Token keamanan", correct_answer: "A", explanation_en: "[SEP] separates sentence pairs in tasks like question answering and entailment.", explanation_id: "[SEP] memisahkan pasangan kalimat dalam tugas seperti question answering dan entailment.", topic: "nlp", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is token type ID?", question_id: "Apa itu token type ID?", option_a_en: "Indicator of which segment/sentence a token belongs to", option_a_id: "Indikator segmen/kalimat mana token tersebut berada", option_b_en: "Token identification", option_b_id: "Identifikasi token", option_c_en: "Type of word", option_c_id: "Tipe kata", option_d_en: "Token classification", option_d_id: "Klasifikasi token", correct_answer: "A", explanation_en: "For sentence pairs: first sentence tokens get 0, second sentence tokens get 1.", explanation_id: "Untuk pasangan kalimat: token kalimat pertama mendapat 0, token kalimat kedua mendapat 1.", topic: "nlp", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What does model.generate() do in transformers?", question_id: "Apa yang dilakukan model.generate() di transformers?", option_a_en: "Auto-regressively generates text given a prompt", option_a_id: "Menghasilkan teks secara auto-regressive berdasarkan prompt", option_b_en: "Creates new models", option_b_id: "Membuat model baru", option_c_en: "Generates embeddings", option_c_id: "Menghasilkan embedding", option_d_en: "Training function", option_d_id: "Fungsi training", correct_answer: "A", explanation_en: "generate() supports various decoding strategies: greedy, beam search, sampling.", explanation_id: "generate() mendukung berbagai strategi decoding: greedy, beam search, sampling.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the Hugging Face Transformers library?", question_id: "Apa itu library Hugging Face Transformers?", option_a_en: "A popular library providing pretrained transformer models", option_a_id: "Library populer yang menyediakan model transformer pretrained", option_b_en: "A company", option_b_id: "Sebuah perusahaan", option_c_en: "A face detection tool", option_c_id: "Alat deteksi wajah", option_d_en: "A hugging app", option_d_id: "Aplikasi pelukan", correct_answer: "A", explanation_en: "Transformers library provides easy access to BERT, GPT, T5, and thousands of models.", explanation_id: "Library Transformers menyediakan akses mudah ke BERT, GPT, T5, dan ribuan model.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is a tokenizer.encode()?", question_id: "Apa itu tokenizer.encode()?", option_a_en: "Converts text to token IDs", option_a_id: "Mengkonversi teks ke ID token", option_b_en: "Encrypts text", option_b_id: "Mengenkripsi teks", option_c_en: "Compresses text", option_c_id: "Mengompresi teks", option_d_en: "Translates text", option_d_id: "Menerjemahkan teks", correct_answer: "A", explanation_en: "encode() tokenizes and converts to IDs. decode() converts IDs back to text.", explanation_id: "encode() melakukan tokenisasi dan mengkonversi ke ID. decode() mengkonversi ID kembali ke teks.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is max_length in tokenization?", question_id: "Apa itu max_length dalam tokenisasi?", option_a_en: "Maximum number of tokens to keep, truncating longer sequences", option_a_id: "Jumlah maksimum token yang disimpan, memotong sequence yang lebih panjang", option_b_en: "Maximum word length", option_b_id: "Panjang kata maksimum", option_c_en: "Maximum sentences", option_c_id: "Kalimat maksimum", option_d_en: "Maximum characters", option_d_id: "Karakter maksimum", correct_answer: "A", explanation_en: "Set max_length based on model's context window. BERT: 512, GPT-3: 4096/8192.", explanation_id: "Atur max_length berdasarkan context window model. BERT: 512, GPT-3: 4096/8192.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is truncation in tokenization?", question_id: "Apa itu truncation dalam tokenisasi?", option_a_en: "Cutting off tokens that exceed max_length", option_a_id: "Memotong token yang melebihi max_length", option_b_en: "Removing words", option_b_id: "Menghapus kata", option_c_en: "Shortening sentences", option_c_id: "Memendekkan kalimat", option_d_en: "Text compression", option_d_id: "Kompresi teks", correct_answer: "A", explanation_en: "truncation=True removes tokens beyond max_length. Usually from the end.", explanation_id: "truncation=True menghapus token di luar max_length. Biasanya dari akhir.", topic: "nlp", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is special_tokens_mask?", question_id: "Apa itu special_tokens_mask?", option_a_en: "Binary mask indicating which tokens are special (CLS, SEP, PAD)", option_a_id: "Mask biner yang menunjukkan token mana yang special (CLS, SEP, PAD)", option_b_en: "Hidden tokens", option_b_id: "Token tersembunyi", option_c_en: "Important tokens", option_c_id: "Token penting", option_d_en: "Masked tokens", option_d_id: "Token yang di-mask", correct_answer: "A", explanation_en: "Useful for excluding special tokens from certain computations.", explanation_id: "Berguna untuk mengecualikan token khusus dari komputasi tertentu.", topic: "nlp", difficulty: "medium", competition: "noai_prelim"},
  # More ML metrics and debugging (10)
  %{question_en: "What is a learning curve?", question_id: "Apa itu learning curve?", option_a_en: "Plot of training and validation performance vs training size/epochs", option_a_id: "Plot performa training dan validasi vs ukuran training/epoch", option_b_en: "Difficulty of learning", option_b_id: "Kesulitan belajar", option_c_en: "Speed of training", option_c_id: "Kecepatan training", option_d_en: "Model architecture", option_d_id: "Arsitektur model", correct_answer: "A", explanation_en: "Learning curves diagnose overfitting (gap), underfitting (both low), and need for more data.", explanation_id: "Learning curve mendiagnosis overfitting (gap), underfitting (keduanya rendah), dan kebutuhan lebih banyak data.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is the validation loss increasing while training loss decreases?", question_id: "Apa artinya validation loss meningkat sementara training loss menurun?", option_a_en: "The model is overfitting", option_a_id: "Model sedang overfitting", option_b_en: "Model is learning well", option_b_id: "Model belajar dengan baik", option_c_en: "Normal behavior", option_c_id: "Perilaku normal", option_d_en: "Underfitting", option_d_id: "Underfitting", correct_answer: "A", explanation_en: "Divergence between train and val loss indicates overfitting. Apply regularization.", explanation_id: "Divergensi antara train dan val loss menunjukkan overfitting. Terapkan regularisasi.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is class imbalance?", question_id: "Apa itu class imbalance?", option_a_en: "When some classes have many more samples than others", option_a_id: "Ketika beberapa kelas memiliki jauh lebih banyak sampel dari yang lain", option_b_en: "Unbalanced weights", option_b_id: "Bobot tidak seimbang", option_c_en: "Model instability", option_c_id: "Ketidakstabilan model", option_d_en: "Feature imbalance", option_d_id: "Ketidakseimbangan fitur", correct_answer: "A", explanation_en: "Class imbalance causes models to favor majority class. Use weighted loss or oversampling.", explanation_id: "Class imbalance menyebabkan model lebih memilih kelas mayoritas. Gunakan weighted loss atau oversampling.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is class weight in loss functions?", question_id: "Apa itu class weight dalam fungsi loss?", option_a_en: "Giving higher importance to underrepresented classes", option_a_id: "Memberikan importance lebih tinggi ke kelas yang kurang terwakili", option_b_en: "Physical weight", option_b_id: "Berat fisik", option_c_en: "Model weights", option_c_id: "Bobot model", option_d_en: "Feature importance", option_d_id: "Importance fitur", correct_answer: "A", explanation_en: "class_weight='balanced' in sklearn computes weights inversely proportional to class frequencies.", explanation_id: "class_weight='balanced' di sklearn menghitung bobot berbanding terbalik dengan frekuensi kelas.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is SMOTE?", question_id: "Apa itu SMOTE?", option_a_en: "Synthetic Minority Over-sampling Technique for handling class imbalance", option_a_id: "Synthetic Minority Over-sampling Technique untuk menangani class imbalance", option_b_en: "Smoke detection", option_b_id: "Deteksi asap", option_c_en: "Smooth operation technique", option_c_id: "Teknik operasi halus", option_d_en: "Small model training", option_d_id: "Training model kecil", correct_answer: "A", explanation_en: "SMOTE creates synthetic samples by interpolating between minority class examples.", explanation_id: "SMOTE membuat sampel sintetis dengan menginterpolasi antara contoh kelas minoritas.", topic: "ml_basics", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is the log loss / binary cross entropy?", question_id: "Apa itu log loss / binary cross entropy?", option_a_en: "-[y*log(p) + (1-y)*log(1-p)] averaged over samples", option_a_id: "-[y*log(p) + (1-y)*log(1-p)] dirata-ratakan pada sampel", option_b_en: "Logarithm of loss", option_b_id: "Logaritma dari loss", option_c_en: "Loss in log scale", option_c_id: "Loss dalam skala log", option_d_en: "Binary loss only", option_d_id: "Hanya loss biner", correct_answer: "A", explanation_en: "Log loss heavily penalizes confident wrong predictions. Range: 0 (perfect) to infinity.", explanation_id: "Log loss sangat menghukum prediksi salah yang percaya diri. Rentang: 0 (sempurna) hingga infinity.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is mean absolute error (MAE)?", question_id: "Apa itu mean absolute error (MAE)?", option_a_en: "Average of absolute differences between predictions and actual values", option_a_id: "Rata-rata perbedaan absolut antara prediksi dan nilai aktual", option_b_en: "Maximum absolute error", option_b_id: "Error absolut maksimum", option_c_en: "Minimum absolute error", option_c_id: "Error absolut minimum", option_d_en: "Average error only", option_d_id: "Hanya rata-rata error", correct_answer: "A", explanation_en: "MAE = mean(|y - y_pred|). Less sensitive to outliers than MSE.", explanation_id: "MAE = mean(|y - y_pred|). Kurang sensitif terhadap outlier daripada MSE.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is R-squared (R²)?", question_id: "Apa itu R-squared (R²)?", option_a_en: "Proportion of variance explained by the model (1 is perfect)", option_a_id: "Proporsi variance yang dijelaskan oleh model (1 adalah sempurna)", option_b_en: "Correlation coefficient", option_b_id: "Koefisien korelasi", option_c_en: "Radius squared", option_c_id: "Radius kuadrat", option_d_en: "Always positive", option_d_id: "Selalu positif", correct_answer: "A", explanation_en: "R² = 1 - (SS_res/SS_tot). Can be negative if model is worse than predicting the mean.", explanation_id: "R² = 1 - (SS_res/SS_tot). Bisa negatif jika model lebih buruk dari memprediksi mean.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is RMSE?", question_id: "Apa itu RMSE?", option_a_en: "Root Mean Squared Error - square root of MSE, same units as target", option_a_id: "Root Mean Squared Error - akar kuadrat dari MSE, satuan sama dengan target", option_b_en: "Random Mean Squared Error", option_b_id: "Random Mean Squared Error", option_c_en: "Relative Mean Squared Error", option_c_id: "Relative Mean Squared Error", option_d_en: "Same as MAE", option_d_id: "Sama dengan MAE", correct_answer: "A", explanation_en: "RMSE = sqrt(MSE). More interpretable than MSE since it's in original units.", explanation_id: "RMSE = sqrt(MSE). Lebih mudah diinterpretasi dari MSE karena dalam satuan asli.", topic: "ml_basics", difficulty: "easy", competition: "noai_prelim"},
  %{question_en: "What is the AUC-ROC?", question_id: "Apa itu AUC-ROC?", option_a_en: "Area Under the ROC Curve - measures classifier's ability to distinguish classes", option_a_id: "Area Under the ROC Curve - mengukur kemampuan classifier membedakan kelas", option_b_en: "Accuracy Under Curve", option_b_id: "Accuracy Under Curve", option_c_en: "Always equals 1", option_c_id: "Selalu sama dengan 1", option_d_en: "Area of confusion matrix", option_d_id: "Area dari confusion matrix", correct_answer: "A", explanation_en: "AUC = 0.5 (random), AUC = 1.0 (perfect). Threshold-independent metric.", explanation_id: "AUC = 0.5 (acak), AUC = 1.0 (sempurna). Metrik independent dari threshold.", topic: "ml_basics", difficulty: "medium", competition: "noai_prelim"},
  # More advanced/emerging (10)
  %{question_en: "What is synthetic data?", question_id: "Apa itu data sintetis?", option_a_en: "Artificially generated data that mimics real data properties", option_a_id: "Data yang dihasilkan secara artifisial yang meniru properti data nyata", option_b_en: "Fake data", option_b_id: "Data palsu", option_c_en: "Clean data", option_c_id: "Data bersih", option_d_en: "Test data", option_d_id: "Data test", correct_answer: "A", explanation_en: "Synthetic data can augment training, protect privacy, or enable testing rare scenarios.", explanation_id: "Data sintetis dapat mengaugmentasi training, melindungi privasi, atau memungkinkan testing skenario langka.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is federated learning?", question_id: "Apa itu federated learning?", option_a_en: "Training models on decentralized data without sharing raw data", option_a_id: "Melatih model pada data terdesentralisasi tanpa berbagi data mentah", option_b_en: "Federal government AI", option_b_id: "AI pemerintah federal", option_c_en: "Centralized training", option_c_id: "Training terpusat", option_d_en: "Distributed computing", option_d_id: "Komputasi terdistribusi", correct_answer: "A", explanation_en: "Federated learning trains on-device, shares only model updates. Privacy-preserving.", explanation_id: "Federated learning melatih di perangkat, hanya berbagi update model. Menjaga privasi.", topic: "advanced", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is model serving?", question_id: "Apa itu model serving?", option_a_en: "Deploying models to make predictions on real-time requests", option_a_id: "Men-deploy model untuk membuat prediksi pada permintaan real-time", option_b_en: "Serving food", option_b_id: "Menyajikan makanan", option_c_en: "Training models", option_c_id: "Melatih model", option_d_en: "Saving models", option_d_id: "Menyimpan model", correct_answer: "A", explanation_en: "Model serving handles inference requests, batching, scaling, and version management.", explanation_id: "Model serving menangani permintaan inferensi, batching, scaling, dan manajemen versi.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is A/B testing for ML models?", question_id: "Apa itu A/B testing untuk model ML?", option_a_en: "Comparing two models by routing traffic to each and measuring outcomes", option_a_id: "Membandingkan dua model dengan merutekan lalu lintas ke masing-masing dan mengukur hasil", option_b_en: "Testing A and B models", option_b_id: "Testing model A dan B", option_c_en: "Alphabet testing", option_c_id: "Testing alfabet", option_d_en: "Binary testing", option_d_id: "Testing biner", correct_answer: "A", explanation_en: "A/B testing validates model improvements on real user interactions with statistical significance.", explanation_id: "A/B testing memvalidasi perbaikan model pada interaksi pengguna nyata dengan signifikansi statistik.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is model drift?", question_id: "Apa itu model drift?", option_a_en: "Degradation of model performance over time due to changing data patterns", option_a_id: "Degradasi performa model seiring waktu karena pola data yang berubah", option_b_en: "Model floating", option_b_id: "Model mengambang", option_c_en: "Model movement", option_c_id: "Pergerakan model", option_d_en: "Model error", option_d_id: "Error model", correct_answer: "A", explanation_en: "Data drift: input distribution changes. Concept drift: relationship between inputs and outputs changes.", explanation_id: "Data drift: distribusi input berubah. Concept drift: hubungan antara input dan output berubah.", topic: "advanced", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is MLOps?", question_id: "Apa itu MLOps?", option_a_en: "Practices for deploying and maintaining ML systems in production", option_a_id: "Praktik untuk men-deploy dan memelihara sistem ML dalam produksi", option_b_en: "ML Operations team", option_b_id: "Tim Operasi ML", option_c_en: "Machine Learning Operators", option_c_id: "Operator Machine Learning", option_d_en: "Model optimization", option_d_id: "Optimisasi model", correct_answer: "A", explanation_en: "MLOps includes CI/CD for ML, monitoring, versioning, reproducibility, and automation.", explanation_id: "MLOps mencakup CI/CD untuk ML, monitoring, versioning, reprodusibilitas, dan otomasi.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is feature store?", question_id: "Apa itu feature store?", option_a_en: "Centralized repository for storing and serving ML features", option_a_id: "Repository terpusat untuk menyimpan dan menyajikan fitur ML", option_b_en: "Feature shop", option_b_id: "Toko fitur", option_c_en: "Data warehouse", option_c_id: "Data warehouse", option_d_en: "Model store", option_d_id: "Penyimpanan model", correct_answer: "A", explanation_en: "Feature stores ensure consistent features between training and inference, enable feature reuse.", explanation_id: "Feature store memastikan fitur konsisten antara training dan inferensi, memungkinkan penggunaan ulang fitur.", topic: "advanced", difficulty: "hard", competition: "noai_prelim"},
  %{question_en: "What is model registry?", question_id: "Apa itu model registry?", option_a_en: "System for versioning, tracking, and managing ML models", option_a_id: "Sistem untuk versioning, tracking, dan mengelola model ML", option_b_en: "Model registration", option_b_id: "Registrasi model", option_c_en: "Registry office", option_c_id: "Kantor registry", option_d_en: "Model database", option_d_id: "Database model", correct_answer: "A", explanation_en: "Model registry tracks model versions, metadata, stage transitions (staging → production).", explanation_id: "Model registry melacak versi model, metadata, transisi tahap (staging → production).", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is edge AI?", question_id: "Apa itu edge AI?", option_a_en: "Running AI models on edge devices (phones, IoT) instead of cloud", option_a_id: "Menjalankan model AI pada edge device (ponsel, IoT) bukan cloud", option_b_en: "AI at the edge of networks", option_b_id: "AI di ujung jaringan", option_c_en: "Cutting-edge AI", option_c_id: "AI mutakhir", option_d_en: "AI boundaries", option_d_id: "Batas AI", correct_answer: "A", explanation_en: "Edge AI enables real-time inference, privacy, and works offline. Requires model optimization.", explanation_id: "Edge AI memungkinkan inferensi real-time, privasi, dan bekerja offline. Membutuhkan optimisasi model.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"},
  %{question_en: "What is AutoML?", question_id: "Apa itu AutoML?", option_a_en: "Automating the process of building and tuning ML models", option_a_id: "Mengotomatisasi proses membangun dan menyetel model ML", option_b_en: "Automatic cars with ML", option_b_id: "Mobil otomatis dengan ML", option_c_en: "Self-learning ML", option_c_id: "ML yang belajar sendiri", option_d_en: "Autonomous ML", option_d_id: "ML otonom", correct_answer: "A", explanation_en: "AutoML automates feature engineering, model selection, hyperparameter tuning.", explanation_id: "AutoML mengotomatisasi feature engineering, pemilihan model, tuning hyperparameter.", topic: "advanced", difficulty: "medium", competition: "noai_prelim"}
]

IO.puts("Inserting bonus questions...")
count = BonusSeeder.insert_all(bonus_questions)
IO.puts("Inserted #{count} bonus questions")

total = Repo.aggregate(Question, :count)
IO.puts("\n=== FINAL TOTAL MCQ QUESTIONS: #{total} ===")
IO.puts("\nTarget: 500+ | Status: #{if total >= 500, do: "ACHIEVED!", else: "Need #{500 - total} more"}")
